import { Product } from '@/types/productType';

export const ProductSampleData: Product[] = [
  {
    id: 'product-004',
    image: 'https://placehold.co/300x300',
    category: 'Electronics',
    name: 'Bluetooth Speaker',
    rating: 4.6,
    reviewCount: 124,
    price: 59.99,
    isWishlisted: false,
    slug: 'bluetooth-speaker',
    description: 'Portable Bluetooth speaker with rich sound and up to 12 hours of battery life.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Bluetooth Speaker',
      },
    ],
    brand: 'SoundWave',
    inStock: true,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },

  {
    id: 'product-005',
    image: 'https://placehold.co/300x300',
    discountPercent: 15,
    category: 'Computers',
    name: 'Mechanical Keyboard',
    rating: 4.8,
    reviewCount: 342,
    price: 84.99,
    originalPrice: 99.99,
    isWishlisted: true,
    slug: 'mechanical-keyboard',
    description: 'Mechanical keyboard with RGB lighting and responsive switches.',
    currency: 'USD',
    compareAtPrice: 99.99,
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Mechanical Keyboard',
      },
    ],
    brand: 'KeyMaster',
    inStock: true,
    variants: [
      {
        id: 'variant-007',
        name: 'Switch',
        value: 'Red',
        inStock: true,
      },
      {
        id: 'variant-008',
        name: 'Switch',
        value: 'Blue',
        inStock: true,
      },
    ],
    createdAt: '2026-08-12T09:00:00Z',
    updatedAt: '2026-09-21T14:00:00Z',
  },

  {
    id: 'product-006',
    image: 'https://placehold.co/300x300',
    category: 'Home',
    name: 'Smart LED Lamp',
    rating: 4.3,
    reviewCount: 76,
    price: 34.99,
    isWishlisted: false,
    slug: 'smart-led-lamp',
    description: 'Smart LED lamp with adjustable brightness and multiple lighting modes.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Smart LED Lamp',
      },
    ],
    brand: 'BrightHome',
    inStock: true,
    variants: [
      {
        id: 'variant-009',
        name: 'Color',
        value: 'White',
        inStock: true,
      },
      {
        id: 'variant-010',
        name: 'Color',
        value: 'Black',
        inStock: false,
      },
    ],
    createdAt: '2026-07-18T11:00:00Z',
    updatedAt: '2026-09-10T15:00:00Z',
  },

  {
    id: 'product-007',
    image: 'https://placehold.co/300x300',
    discountPercent: 25,
    category: 'Gaming',
    name: 'Gaming Headset',
    rating: 4.4,
    reviewCount: 198,
    price: 74.99,
    originalPrice: 99.99,
    isWishlisted: false,
    slug: 'gaming-headset',
    description: 'Gaming headset with surround sound and a noise-cancelling microphone.',
    currency: 'USD',
    compareAtPrice: 99.99,
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Gaming Headset',
      },
    ],
    brand: 'GameSound',
    inStock: true,
    createdAt: '2026-08-01T13:00:00Z',
    updatedAt: '2026-09-19T10:00:00Z',
  },

  {
    id: 'product-008',
    image: 'https://placehold.co/300x300',
    category: 'Accessories',
    name: 'Leather Wallet',
    rating: 4.5,
    reviewCount: 65,
    price: 39.99,
    isWishlisted: true,
    slug: 'leather-wallet',
    description: 'Compact leather wallet with multiple card slots and a cash compartment.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Leather Wallet',
      },
    ],
    brand: 'UrbanCraft',
    inStock: true,
    variants: [
      {
        id: 'variant-011',
        name: 'Color',
        value: 'Brown',
        inStock: true,
      },
      {
        id: 'variant-012',
        name: 'Color',
        value: 'Black',
        inStock: true,
      },
    ],
    createdAt: '2026-06-25T08:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
  },

  {
    id: 'product-009',
    image: 'https://placehold.co/300x300',
    category: 'Fitness',
    name: 'Resistance Bands',
    rating: 4.6,
    reviewCount: 287,
    price: 24.99,
    isWishlisted: false,
    slug: 'resistance-bands',
    description: 'Set of resistance bands for strength training and home workouts.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Resistance Bands',
      },
    ],
    brand: 'FitGear',
    inStock: true,
    variants: [
      {
        id: 'variant-013',
        name: 'Resistance',
        value: 'Light',
        inStock: true,
      },
      {
        id: 'variant-014',
        name: 'Resistance',
        value: 'Heavy',
        inStock: true,
      },
    ],
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-09-17T13:00:00Z',
  },

  {
    id: 'product-010',
    image: 'https://placehold.co/300x300',
    discountPercent: 12,
    category: 'Home',
    name: 'Coffee Maker',
    rating: 4.2,
    reviewCount: 143,
    price: 87.99,
    originalPrice: 99.99,
    isWishlisted: false,
    slug: 'coffee-maker',
    description: 'Programmable coffee maker with a 12-cup capacity and automatic shutoff.',
    currency: 'USD',
    compareAtPrice: 99.99,
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Coffee Maker',
      },
    ],
    brand: 'BrewMaster',
    inStock: true,
    createdAt: '2026-08-10T09:30:00Z',
    updatedAt: '2026-09-20T16:00:00Z',
  },

  {
    id: 'product-011',
    image: 'https://placehold.co/300x300',
    category: 'Clothing',
    name: 'Classic Hoodie',
    rating: 4.7,
    reviewCount: 421,
    price: 54.99,
    isWishlisted: true,
    slug: 'classic-hoodie',
    description: 'Comfortable cotton-blend hoodie designed for everyday wear.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Classic Hoodie',
      },
    ],
    brand: 'EverydayWear',
    inStock: true,
    variants: [
      {
        id: 'variant-015',
        name: 'Size',
        value: 'Medium',
        inStock: true,
      },
      {
        id: 'variant-016',
        name: 'Size',
        value: 'Large',
        inStock: true,
      },
      {
        id: 'variant-017',
        name: 'Size',
        value: 'XL',
        inStock: false,
      },
    ],
    createdAt: '2026-08-28T12:00:00Z',
    updatedAt: '2026-09-22T09:00:00Z',
  },

  {
    id: 'product-012',
    image: 'https://placehold.co/300x300',
    discountPercent: 20,
    category: 'Electronics',
    name: 'Wireless Charger',
    rating: 4.1,
    reviewCount: 94,
    price: 31.99,
    originalPrice: 39.99,
    isWishlisted: false,
    slug: 'wireless-charger',
    description: 'Fast wireless charging pad compatible with a wide range of smartphones.',
    currency: 'USD',
    compareAtPrice: 39.99,
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Wireless Charger',
      },
    ],
    brand: 'ChargeTech',
    inStock: true,
    createdAt: '2026-08-05T14:00:00Z',
    updatedAt: '2026-09-18T17:00:00Z',
  },

  {
    id: 'product-013',
    image: 'https://placehold.co/300x300',
    category: 'Outdoor',
    name: 'Travel Backpack',
    rating: 4.8,
    reviewCount: 176,
    price: 89.99,
    isWishlisted: false,
    slug: 'travel-backpack',
    description: 'Durable travel backpack with laptop storage and multiple compartments.',
    currency: 'USD',
    images: [
      {
        url: 'https://placehold.co/600x600',
        alt: 'Travel Backpack',
      },
    ],
    brand: 'TrailPack',
    inStock: true,
    variants: [
      {
        id: 'variant-018',
        name: 'Color',
        value: 'Black',
        inStock: true,
      },
      {
        id: 'variant-019',
        name: 'Color',
        value: 'Blue',
        inStock: true,
      },
    ],
    createdAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
];

const sampleImages = [
  'https://media.istockphoto.com/id/1220752009/photo/black-wireless-headphone-on-white-background-headphone-isolated-on-a-white-background-product.jpg?s=1024x1024&w=is&k=20&c=EgBJSRILgVFkoY8QRpJcpOJgnHHmrqG13XIHaGjvKp0=',
  'https://media.istockphoto.com/id/1480789361/photo/light-purple-wireless-headphone-on-isolated-white-background-product-photography-fashion-item.jpg?s=1024x1024&w=is&k=20&c=53azT3bnpz1Kmi3MD_C5A0LoSu1M0Otjc7td8VqoDd8=',
  'https://media.istockphoto.com/id/1373472480/photo/black-audio-headphones-isolated-on-white-background.jpg?s=1024x1024&w=is&k=20&c=Al8-PYX9skR0ODCiSr2d5F1hiA22OZac05-ony-MDlw=',
  'https://media.istockphoto.com/id/1175203328/photo/3d-render-image-of-modern-coral-colored-audio-headphones-on-a-white.jpg?s=1024x1024&w=is&k=20&c=sUvz8TGyHdjCuMKcp91rAG4UzFyMv-zFTgHUtqOaqzA=',
  'https://media.istockphoto.com/id/942462608/photo/headphone-black-color.jpg?s=1024x1024&w=is&k=20&c=sRlzBOm3JCbCkgg9yTVc_zMAApg4BV0WSXcdz-c_QIc=',
];

export const getSampleImages = (count: number): string[] => {
  return sampleImages.slice(0, count);
};
